logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
    sql: debug

spring:
  application:
    name: cave-a-vin
  profiles:
    active: dev
  messages:
    encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver