version: '3.8'
services:
    mongodb:
        image: mongo
        container_name: mongo_demo
        ports:
            - "27017:27017"
        volumes:
            - mongo_demo:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=sa
            - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
        restart: unless-stopped
    mongo-express:
        image: mongo-express
        container_name: mongo_express_demo
        ports:
            - "8081:8081"
        depends_on:
            - mongodb
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=sa
            - ME_CONFIG_MONGODB_ADMINPASSWORD=Passw0rd
            - ME_CONFIG_MONGODB_SERVER=mongodb
        restart: unless-stopped

volumes:
    mongo_demo: {}
